name: HA Docker Cleaner
version: "1.0.3"
slug: ha_docker_cleaner
description: Automatically prunes unused Docker images and stopped containers
url: "https://github.com/tomtomdk/ha-docker-cleaner"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false
docker_api: true
host_network: false

map:
  - type: share
    read_only: false

options:
  run_day: "sun"
  run_hour: 4
  prune_images: true
  prune_containers: true
  prune_builder: false
  prune_volumes: false

schema:
  run_day: list(mon|tue|wed|thu|fri|sat|sun)
  run_hour: int(0,23)
  prune_images: bool
  prune_containers: bool
  prune_builder: bool
  prune_volumes: bool